version: 0.1
log:
  level: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
http:
  addr: :5000
  net: tcp
  secret: asecretforlocaldevelopment
  debug:
    addr: :5001
notifications:
  endpoints:
    - name: alistener
      disabled: false
      url: http://192.168.21.117:8080/v1/registry/event
      headers:
        Authorization:
        - just4fun
      timeout: 500ms
      threshold: 5
      backoff: 3s
      ignoredmediatypes:
        - application/octet-stream