apiVersion: v1
kind: List
items:
# rabbitmq config

- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: rabbitmq-server
    namespace: boxlinker
    labels:
      name: rabbitmq-server
      rc-krud: "boxlinker_centos-rabbitmq"
  spec:
    replicas: 1
    selector:
      name: rabbitmq-server
    template:
      metadata:
        labels:
          name: rabbitmq-server
          logs: boxlinker-rabbitmq-server
      spec:
        nodeSelector:
          role: system
        imagePullSecrets:
        - name: registry-key
        containers:
        - name: rabbitmq-server
          imagePullPolicy: Always
          image: index.boxlinker.com/boxlinker/centos-rabbitmq:1.0.1
          ports:
          - containerPort: 5672

- apiVersion: v1
  kind: Service
  metadata:
    name: rabbitmq-server
    namespace: boxlinker
    labels:
      name: rabbitmq-server
    annotations:
      serviceloadbalancer/lb.tcp: "30002:5672"
      serviceloadbalancer/lb.node: "main"
  spec:
    selector:
      name: rabbitmq-server
    sessionAffinity: ClientIP
    ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
