apiVersion: v1
kind: Service
metadata:
    name: database
    namespace: boxlinker
    labels:
        name: database
spec:
    selector:
      db: db-cluster
    sessionAffinity: ClientIP
    ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
