apiVersion: v1
kind: List
items:
# storage config

- apiVersion: v1
  kind: Service
  metadata:
    name: storage
    namespace: boxlinker
    labels:
      name: storage
    annotations:
      serviceloadbalancer/lb.http: storage.boxlinker.com:8001
      serviceloadbalancer/lb.node: main
      serviceloadbalancer/lb.sslTerm: "true"
  spec:
    ports:
    - port: 8001
      targetPort: 8001

- apiVersion: v1
  kind: Endpoints
  metadata:
    name: storage
    namespace: boxlinker
  subsets:
    - addresses:
      - ip: 172.20.1.7
      ports:
        - port: 8001
