apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: k8s-api
    namespace: boxlinker
    annotations:
      serviceloadbalancer/lb.http: api.boxlinker.com:9000
      serviceloadbalancer/lb.node: main
  spec:
    selector:
      component: k8s-api
    ports:
    - port: 9000
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: k8s-api
    namespace: boxlinker
    labels:
      component: k8s-api
      rc-krud: boxlinker_centos-k8sapi
  spec:
    replicas: 1
    template:
      metadata:
        name: k8s-api
        namespace: boxlinker
        labels:
          logs: boxlinker-k8s-api
          name: k8s-api
          component: k8s-api
      spec:
        nodeSelector:
          role: node
        imagePullSecrets:
        - name: registry-key
        containers:
        - name: k8s-api
          image: index.boxlinker.com/boxlinker/centos-k8sapi:1.0.0
          imagePullPolicy: Always
          env:
          - name: MYSQL_HOST
            value: database
          - name: MYSQL_PORT
            value: "3306"
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: STORAGE_HOST
            value: storage-api:9999
          - name: AUTHOR_HOST
            value: registry-api:8080
          - name: ELASTIC_SEARCH
            value: elasticsearch:9200
          ports:
          - containerPort: 9000