apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: service-loadbalancer
    namespace: boxlinker
    labels:
      rc-krud: "boxlinker_servicelb_0.44"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          component: service-loadbalancer
      spec:
        nodeSelector:
          role: loadbalancer
        imagePullSecrets:
        - name: registry-key
        containers:
        - image: index.boxlinker.com/boxlinker/servicelb:0.44
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          name: haproxy
          ports:
          # All http services
          - containerPort: 80
            hostPort: 80
            protocol: TCP
          # haproxy stats
          - containerPort: 1936
            hostPort: 1936
            protocol: TCP
          resources: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: lb-test
    namespace: boxlinker
    annotations:
      serviceloadbalancer/lb.host: lb-test.boxlinker.com
    labels:
      component: lb-test
  spec:
    selector:
      component: lb-test
    ports:
    - port: 80
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: lb-test
    namespace: boxlinker
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          component: lb-test
      spec:
        nodeSelector:
          role: node
        imagePullSecrets:
        - name: registry-key
        containers:
        - image: index.boxlinker.com/library/nginx
          name: lb-test
          ports:
          - containerPort: 80
