apiVersion: v1
kind: ReplicationController
metadata:
  name: service-loadbalancer
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-loadbalancer
    spec:
      nodeSelector:
        role: loadbalancer
      containers:
      - image: index.36ap.com/servicelb:0.43
        #imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: haproxy
        ports:
        # All http services
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        # haproxy stats
        - containerPort: 1936
          hostPort: 1936
          protocol: TCP
        resources: {}
#        args:
#        - --insecure-skip-tls-verify=true
#        - --use-kubernetes-cluster-service=false
#        - --server=192.168.1.21:8080
#        - --forward-services=true
