apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: ci-api
    namespace: boxlinker
    labels:
      component: ci-api
    annotations:
      serviceloadbalancer/lb.http: "ci-api.boxlinker.com:8080"
      serviceloadbalancer/lb.node: "main"
  spec:
    selector:
      component: ci-api
    ports:
    - port: 8080
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: ci-api
    namespace: boxlinker
    labels:
      component: ci-api
      rc-krud: "boxlinker_ci-api"
  spec:
    replicas: 1
    selector:
      component: ci-api
    template:
      metadata:
        name: ci-api
        labels:
          component: ci-api
      spec:
        nodeSelector:
          role: node
        imagePullSecrets:
        - name: registry-key
        containers:
        - name: ci-api
          image: index.boxlinker.com/boxlinker/ci-api:1.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          command:
          - /app/controller
          - -D 
          - server
          - --use-kubernetes-cluster-service
# todo 这里指定为内网地址后，返回的信息是空 {0, map[],}          
#- --auth-url=http://registry-api:8080
