apiVersion: v1
kind: Service
metadata:
    name: haproxy
    labels:
        name: haproxy
spec:
    type: NodePort
    selector:
        name: haproxy
    ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
      nodePort: 30005
    - name: nginx
      port: 80
      targetPort: 80
      nodePort: 30006

