apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: kube-dns
    namespace: boxlinker
    labels:
      component: kube-dns
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: "KubeDNS"
  spec:
    selector:
      component: kube-dns
    clusterIP: 10.254.10.10
    ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: k8s-dns-v8
    namespace: boxlinker
    labels:
      component: kube-dns
      version: v8
      kubernetes.io/cluster-service: "true"
  spec:
    replicas: 1
    selector:
      component: kube-dns
      version: v8
    template:
      metadata:
        namespace: boxlinker
        labels:
          component: kube-dns
          version: v8
          kubernetes.io/cluster-service: "true"
      spec:
        nodeSelector:
          role: system
        imagePullSecrets:
        - name: registry-key
        containers:
        - name: etcd
          image: index.boxlinker.com/google_containers/etcd:2.0.9
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          command:
          - /usr/local/bin/etcd
          - -data-dir
          - /var/etcd/data
          - -listen-client-urls
          - http://127.0.0.1:2379,http://127.0.0.1:4001
          - -advertise-client-urls
          - http://127.0.0.1:2379,http://127.0.0.1:4001
          - -initial-cluster-token
          - skydns-etcd
          volumeMounts:
          - name: etcd-storage
            mountPath: /var/etcd/data
        - name: kube2sky
          image: index.boxlinker.com/google_containers/kube2sky:1.11
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
          - name: kubeconfig
            mountPath: /etc/kubeconfig
            readOnly: true
          - name: ssl
            mountPath: /opt/kubernetes/ssl
            readOnly: true
          args:
          # command = "/kube2sky"
          - --kube_master_url=https://172.20.1.16:443
          - -kubecfg_file=/etc/kubeconfig
          - -domain=cluster.local
        - name: skydns
          image: index.boxlinker.com/google_containers/skydns:2015-03-11-001
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          args:
          # command = "/skydns"
          - -machines=http://localhost:4001
          - -addr=0.0.0.0:53
          - -domain=cluster.local
          ports:
          - containerPort: 53
            name: dns
            protocol: UDP
          - containerPort: 53
            name: dns-tcp
            protocol: TCP
        volumes:
        - name: etcd-storage
          emptyDir: {}
        - name: kubeconfig
          hostPath:
            path: /opt/kubernetes/cfg/kubeconfig
        - name: ssl
          hostPath:
            path: /opt/kubernetes/ssl
        dnsPolicy: Default
- apiVersion: v1
  kind: Pod
  metadata:
    namespace: boxlinker
    name: busybox
  spec:
    nodeSelector:
      role: system
    imagePullSecrets:
    - name: registry-key
    containers:
    - image: index.boxlinker.com/google_containers/busybox
      command:
      - sleep
      - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
