# go build && ./cmd -D --rabbitmq-host=boxlinker.com --rabbitmq-port=30001 --rabbitmq-exchange-name=build_code_exchang_debug --db=postgres://postgres:postgres@127.0.0.1/postgres?sslmode=disable
# cd src/github.com/cabernety/boxlinker/platform/building/cmd

postgres:
  image: postgres
  ports:
  - 5432:5432
phppgadmin:
  image: jacksoncage/phppgadmin
  ports:
  - 8080:80
  links:
  - postgres:postgres
  environment:
  - POSTGRES_HOST=postgres
  - POSTGRES_PORT=5432
  - POSTGRES_DEFAULTDB=postgres