#!/bin/sh

if ! test -d ~git/.ssh; then
    mkdir -p ~git/.ssh
    chmod 700 ~git/.ssh
fi

if ! test -f ~git/.ssh/environment; then
    echo "BLG_CUSTOM=${BLG_CUSTOM}" > ~git/.ssh/environment
    chmod 600 ~git/.ssh/environment
fi

cd /app/boxlinker-git

# Link volumed data with app data
ln -sf /data/boxlinker-git/log  ./log
ln -sf /data/boxlinker-git/data ./data

# Backward Compatibility with Gogs Container v0.6.15
ln -sf /data/git /home/git

chown -R git:git /data /app/boxlinker-git ~git/
chmod 0755 /data /data/boxlinker-git ~git/
