apiVersion: v1
kind: Service
metadata:
    name: rabbitmq
    namespace: boxlinker
    labels:
        name: rabbitmq
    annotations:
        serviceloadbalancer/lb.tcp: "30001:5672"
        serviceloadbalancer/lb.node: "main"
spec:
    sessionAffinity: ClientIP
    ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
