apiVersion: v1
kind: Secret
metadata:
  name: registry-key
  namespace: boxlinker
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJpbmRleC5ib3hsaW5rZXIuY29tIjogewoJCQkiYXV0aCI6ICJZbTk0YkdsdWEyVnlPbEZCV25kemVERXlNdz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson