apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: k8s-api
    namespace: boxlinker
    annotations:
      serviceloadbalancer/lb.host: api.boxlinker.com
  spec:
    selector:
      component: k8s-api
    ports:
    - port: 9000
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: k8s-api
    namespace: boxlinker
    labels:
      component: k8s-api
      rc-krud: boxlinker_centos-k8sapi_latest
  spec:
    replicas: 1
    template:
      metadata:
        name: k8s-api
        namespace: boxlinker
        labels:
          name: k8s-api
          component: k8s-api
      spec:
        nodeSelector:
          role: node
        imagePullSecrets:
        - name: registry-key
        containers:
        - name: k8s-api
          image: index.boxlinker.com/boxlinker/centos-k8sapi:latest
          imagePullPolicy: Always
          env:
          - name: MYSQL_HOST
            value: database
          - name: MYSQL_PORT
            value: "3306"
          - name: RABBITMQ_HOST
            value: rabbitmq
          ports:
          - containerPort: 9000
