apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: test-mysql
    namespace: boxlinker
  spec:
    selector:
      component: test-mysql
    ports:
    - port: 3306
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: test-mysql
    namespace: boxlinker
  spec:
    replicas: 1
    template:
      metadata:
        name: test-mysql
        namespace: boxlinker
        labels:
          component: test-mysql
      spec:
        nodeSelector:
          role: node
        containers:
        - name: test-mysql
          image: index.boxlinker.com/library/mysql
          imagePullPolicy: Always
          env:
          - name: MYSQL_DATABASE
            value: clouddata
          - name: MYSQL_USER
            value: cloud
          - name: MYSQL_PASSWORD
            value: cloud
          ports:
          - containerPort: 3306