apiVersion: v1
kind: Service
metadata:
    name: database
    namespace: boxlinker
    labels:
        name: database
    annotations:
      # `30101` 指的就是 tcp 服务在 lb server 上绑定的端口, 同一个 lb server 上需要唯一
      # 端口范围再讨论, 暂定 30000 ~ 31000
      serviceloadbalancer/lb.tcp: "30000:3306"
      serviceloadbalancer/lb.node: "main"
spec:
    selector:
      db: db-cluster
    sessionAffinity: ClientIP
    ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
