apiVersion: v1
kind: List
items:
# grafana
- apiVersion: v1
  kind: Service
  metadata:
    namespace: boxlinker
    labels:
      kubernetes.io/cluster-service: 'true'
      kubernetes.io/name: monitoring-grafana
    name: monitoring-grafana
    annotations:
      serviceloadbalancer/lb.http: grafana.boxlinker.com:3000
      serviceloadbalancer/lb.node: main
  spec:
    # In a production setup, we recommend accessing Grafana through an external Loadbalancer
    # or through a public IP.
    # type: LoadBalancer
    ports:
    - port: 3000
    selector:
      name: grafana
- apiVersion: v1
  kind: ReplicationController
  metadata:
    namespace: boxlinker
    labels:
      name: grafana
    name: grafana
  spec:
    replicas: 1
    selector:
      name: grafana
    template:
      metadata:
        namespace: boxlinker
        labels:
          name: grafana
      spec:
        nodeSelector:
          role: node
        imagePullSecrets:
        - name: registry-key
        containers:
        - name: grafana
          image: index.boxlinker.com/boxlinker/heapster_grafana:v1.2.0-beta.0
          imagePullPolicy: Always
          env:
            - name: INFLUXDB_SERVICE_URL
              value: http://monitoring-influxdb:8086
          volumeMounts:
          - mountPath: /var
            name: grafana-storage
          ports:
          - containerPort: 3000
        volumes:
        - name: grafana-storage
          emptyDir: {}
# heapster
- apiVersion: v1
  kind: Service
  metadata:
    namespace: boxlinker
    labels:
      kubernetes.io/cluster-service: 'true'
      kubernetes.io/name: Heapster
    annotations:
      serviceloadbalancer/lb.http: heapster.boxlinker.com:8082
      serviceloadbalancer/lb.node: main
    name: heapster
  spec:
    ports:
    - port: 8082
      targetPort: 8082
    selector:
      k8s-app: heapster
- apiVersion: v1
  kind: ReplicationController
  metadata:
    namespace: boxlinker
    labels:
      k8s-app: heapster
      name: heapster
      version: v6
    name: heapster
  spec:
    replicas: 1
    selector:
      k8s-app: heapster
      version: v6
    template:
      metadata:
        namespace: boxlinker
        labels:
          k8s-app: heapster
          version: v6
      spec:
        nodeSelector:
          role: node
        imagePullSecrets:
        - name: registry-key
        containers:
        - name: heapster
          #image: kubernetes/heapster:v1.2.0-beta.0
          image: index.boxlinker.com/boxlinker/heapster:v1.2.0-beta.0
          imagePullPolicy: Always
          command:
          - /heapster
          - --source=kubernetes:https://kubernetes.default
          - --sink=influxdb:http://monitoring-influxdb:8086
- apiVersion: v1
  kind: Service
  metadata:
    namespace: boxlinker
    labels: null
    name: monitoring-influxdb
    annotations:
      serviceloadbalancer/lb.http: influxdb.boxlinker.com:8086,influxadmin.boxlinker.com:8083
      serviceloadbalancer/lb.node: main
  spec:
    ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: api
      port: 8086
      targetPort: 8086
    selector:
      name: influxdb
- apiVersion: v1
  kind: ReplicationController
  metadata:
    namespace: boxlinker
    labels:
      name: influxdb
    name: influxdb
  spec:
    replicas: 1
    selector:
      name: influxdb
    template:
      metadata:
        namespace: boxlinker
        labels:
          name: influxdb
      spec:
        nodeSelector:
          role: node
        imagePullSecrets:
        - name: registry-key
        containers:
        - name: influxdb
          image: index.boxlinker.com/boxlinker/heapster_influxdb:v1.2.0-beta.0
          imagePullPolicy: Always
          #kubernetes/heapster_influxdb:v0.5
          volumeMounts:
          - mountPath: /data
            name: influxdb-storage
        volumes:
        - name: influxdb-storage
          emptyDir: {}

