apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      serviceAccountName: heapster
      containers:
      - name: grafana
        image: gcr.io/google_containers/heapster_grafana:v1.2.0-beta.0
        env:
          - name: INFLUXDB_SERVICE_URL
            value: http://monitoring-influxdb:8086
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - name: grafana-storage
        emptyDir: {}
