apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    name: influxdb
  template:
    metadata:
      labels:
        name: influxdb
    spec:
      serviceAccountName: heapster
      containers:
      - name: influxdb
        image: gcr.io/google_containers/heapster_influxdb:v1.2.0-beta.0 
        #kubernetes/heapster_influxdb:v0.5
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
