apiVersion: v1
kind: ReplicationController
metadata:
  name: log-test
  namespace: boxlinker
  labels:
    logs: log-test
    component: log-test
spec:
  replicas: 1
  template:
    metadata:
      name: log-test
      namespace: boxlinker
      labels:
        logs: log-test
        component: log-test
    spec:
      nodeSelector:
        test: "true"
      imagePullSecrets:
      - name: registry-key
      containers:
      - name: logtest
        image: index.boxlinker.com/boxlinker/centos:7
        args: [bash, -c,
                'for ((i=0; ; i++)); do if [ $(expr ${i} % 2) -eq 0 ]; then echo "{\"userid\":\"boxlinker\",\"log\":\"$i: $(date)\"}"; else echo "{\"userid\":\"user1\",\"log\":\"$i: $(date)111\"}"; fi; sleep 1; done']
