version: '2'
services:
#  nginx:
#    image: index.boxlinker.com/boxlinker/nginx-true:latest
#    links:
#    - imagerepo:imagerepo
#    volumes:
#    - ./registry/auth-nginx/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#    - 80:80
#    - 443:443


#docker run -itd -h rabbitmq -p 5672:5672 index.boxlinker.com/library/rabbitmq
#  nginx:
#    image: index.boxlinker.com/boxlinker/nginx-true:latest
#    links:
#    - imagerepo:imagerepo
#    volumes:
#    - ./registry/auth-nginx/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#    - 80:80
#    - 443:443
  imagerepo-apiserver:
    image: index.boxlinker.com/boxlinker/imagerepo-base:latest
    restart: always
    links:
    - rabbitmq:rabbitmq
    command: python /ImageRepo/imageAuth/restserver/restapi_server.py
    volumes:
    - "./common:/ImageRepo/common/"
    - "./imageAuth:/ImageRepo/imageAuth/"
    - "./conf:/ImageRepo/conf/"
    - "./pyTools:/ImageRepo/pyTools/"
    - "./registry:/ImageRepo/registry/"
    - "/etc/hosts:/etc/hosts"
    ports:
    - 8843:8001
  imagerepo-callserver:
    image: index.boxlinker.com/boxlinker/imagerepo-base:latest
    restart: always
    command: python /ImageRepo/imageAuth/rpcserver/rpcapi_callserver.py
    links:
    - rabbitmq:rabbitmq
    volumes:
    - "./common:/ImageRepo/common/"
    - "./imageAuth:/ImageRepo/imageAuth/"
    - "./conf:/ImageRepo/conf/"
    - "./pyTools:/ImageRepo/pyTools/"
    - "./registry:/ImageRepo/registry/"
    - "/etc/hosts:/etc/hosts"
    ports:
    - 8844:8001
  rabbitmq:
    image: index.boxlinker.com/library/rabbitmq
    volumes:
    - "/etc/hosts:/etc/hosts"
    ports:
    - 5672:5672