apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: registry-api
    namespace: boxlinker
    annotations:
      serviceloadbalancer/lb.http: auth.boxlinker.com:8080
      serviceloadbalancer/lb.node: main
  spec:
    ports:
    - port: 8080
- apiVersion: v1
  kind: Endpoints
  metadata:
    name: registry-api
    namespace: boxlinker
  subsets:
  - ports:
    - port: 8080
    addresses:
    - ip: "192.168.1.15"
# root/root123
