apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: gitlab-ce
    namespace: boxlinker
    annotations:
      serviceloadbalancer/lb.http: git.boxlinker.com:80
      serviceloadbalancer/lb.node: main
    labels:
      app: gitlab-ce
  spec:
    selector:
      app: gitlab-ce
    ports:
    - name: http
      port: 80
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: gitlab-ce
    namespace: boxlinker
    labels:
      app: gitlab-ce
  spec:
    replicas: 1
    selector:
      app: gitlab-ce
    template:
      metadata:
        labels:
          app: gitlab-ce
      spec:
        nodeSelector:
          role: node
        imagePullSecrets:
        - name: registry-key
        containers:
        - name: gitlab-ce
          image: index.boxlinker.com/boxlinker/gitlab:8.10.4
          ports:
          - containerPort: 80
          - containerPort: 22
          env:
          - name: DEBUG
            value: "true"
          - name: DB_ADAPTER
            value: "postgresql"
          - name: DB_HOST
            value: "gitlab-postgresql.boxlinker.svc"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "gitlab"
          - name: DB_PASS
            value: "just4fun"
          - name: DB_NAME
            value: "gitlabhq_production"
          - name: REDIS_HOST
            value: "gitlab-redis.boxlinker.svc"
          - name: REDIS_PORT
            value: "6379"
          - name: TZ
            value: "Asia/Shanghai"
          - name: GITLAB_TIMEZONE
            value: "Beijing"

          - name: GITLAB_HTTPS
            value: "false"
          - name: SSL_SELF_SIGNED
            value: "false"

          - name: GITLAB_HOST
            value: "git.boxlinker.com"
#          - name: GITLAB_PORT
#            value: "80"
#          - name: GITLAB_SSH_PORT
#            value: "22"
          - name: GITLAB_SECRETS_DB_KEY_BASE
            value: "long-and-random-alpha-numeric-string"
          - name: GITLAB_ROOT_PASSWORD
            value: "just4fun"
          - name: GITLAB_ROOT_EMAIL
            value: "330785652@qq.com"
          volumeMounts:
          - name: gitlab-data
            mountPath: /home/git/data
        volumes:
        - name: gitlab-data
          rbd:
            monitors:
            - "192.168.1.9:5000"
            - "192.168.1.8:5000"
            - "192.168.1.5:5000"
            pool: pool_hdd
            image: kube-systemc_gitlab_gitlab
            user: admin
            keyring: /etc/ceph/keyring
            secretRef: null
            fsType: xfs
            readOnly: false
##### redis #######
- apiVersion: v1
  kind: Service
  metadata:
    name: gitlab-redis
    namespace: boxlinker
    labels:
      app: gitlab-redis
  spec:
    selector:
      app: gitlab-redis
    ports:
    - name: tcp
      port: 6379
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: gitlab-redis
    namespace: boxlinker
    labels:
      app: gitlab-redis
  spec:
    replicas: 1
    selector:
      app: gitlab-redis
    template:
      metadata:
        labels:
          app: gitlab-redis
      spec:
        nodeSelector:
          role: node
        imagePullSecrets:
        - name: registry-key
        containers:
        - name: gitlab-redis
          image: index.boxlinker.com/library/redis:latest
          args:
          - --loglevel warning
          ports:
          - containerPort: 6379
          volumeMounts:
          - name: redis-data
            mountPath: /var/lib/redis
        volumes:
        - name: redis-data
          rbd:
            monitors:
            - "192.168.1.9:5000"
            - "192.168.1.8:5000"
            - "192.168.1.5:5000"
            pool: pool_hdd
            image: kube-systemc_gitlab_redis
            user: admin
            keyring: /etc/ceph/keyring
            secretRef: null
            fsType: xfs
            readOnly: false
##### postgresql #######
- apiVersion: v1
  kind: Service
  metadata:
    name: gitlab-postgresql
    namespace: boxlinker
    labels:
      app: gitlab-postgresql
  spec:
    selector:
      app: gitlab-postgresql
    ports:
    - name: tcp
      port: 5432
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: gitlab-postgresql
    namespace: boxlinker
    labels:
      app: gitlab-postgresql
  spec:
    replicas: 1
    selector:
      app: gitlab-postgresql
    template:
      metadata:
        labels:
          app: gitlab-postgresql
      spec:
        nodeSelector:
          role: node
        imagePullSecrets:
        - name: registry-key
        containers:
        - name: gitlab-postgresql
          image: index.boxlinker.com/library/postgresql:9.5
          env:
          - name: DB_USER
            value: "gitlab"
          - name: DB_PASS
            value: "just4fun"
          - name: DB_NAME
            value: "gitlabhq_production"
          - name: DB_EXTENSION
            value: "pg_trgm"
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: postgresql-data
            mountPath: /var/lib/postgresql
        volumes:
        - name: postgresql-data
          rbd:
            monitors:
            - "192.168.1.9:5000"
            - "192.168.1.8:5000"
            - "192.168.1.5:5000"
            pool: pool_hdd
            image: kube-system_gitlab_postgresql
            user: admin
            keyring: /etc/ceph/keyring
            secretRef: null
            fsType: xfs
            readOnly: false