apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: redis
        image: regbl.com/sameersbn/redis:latest
        args:
        - --loglevel warning
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /var/lib/redis
      - name: postgresql
        image: regbl.com/sameersbn/postgresql:9.5
        env:
        - name: DB_USER
          value: "gitlab"
        - name: DB_PASS
          value: "just4fun"
        - name: DB_NAME
          value: "gitlabhq_production"
        - name: DB_EXTENSION
          value: "pg_trgm"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql
      - name: gitlab
        image: regbl.com/sameersbn/gitlab:8.10.4
        ports:
        - containerPort: 80
        - containerPort: 22
        env:
        - name: DEBUG
          value: "true"
        - name: DB_ADAPTER
          value: "postgresql"
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "gitlab"
        - name: DB_PASS
          value: "just4fun"
        - name: DB_NAME
          value: "gitlabhq_production"
        - name: REDIS_HOST
          value: "localhost"
        - name: REDIS_PORT
          value: "6379"
        - name: TZ
          value: "Asia/Shanghai"
        - name: GITLAB_TIMEZONE
          value: "Beijing"

        - name: GITLAB_HTTPS
          value: "false"
        - name: SSL_SELF_SIGNED
          value: "false"

        - name: GITLAB_HOST
          value: "git.36ap.com"
        - name: GITLAB_PORT
          value: "10080"
        - name: GITLAB_SSH_PORT
          value: "10022"
        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: "long-and-random-alpha-numeric-string"
        - name: GITLAB_ROOT_PASSWORD
          value: "just4fun"
        - name: GITLAB_ROOT_EMAIL
          value: "330785652@qq.com"
        volumeMounts:
        - name: gitlab-data
          mountPath: /home/git/data
      volumes:
      - name: redis-data
        rbd:
          monitors:
          - "192.168.1.9:5000"
          - "192.168.1.8:5000"
          - "192.168.1.5:5000"
          pool: pool_hdd
          image: kube-systemc_gitlab_redis
          user: admin
          keyring: /etc/ceph/keyring
          secretRef: null
          fsType: xfs
          readOnly: false
      - name: postgresql-data
        rbd:
          monitors:
          - "192.168.1.9:5000"
          - "192.168.1.8:5000"
          - "192.168.1.5:5000"
          pool: pool_hdd
          image: kube-system_gitlab_postgresql
          user: admin
          keyring: /etc/ceph/keyring
          secretRef: null
          fsType: xfs
          readOnly: false
      - name: gitlab-data
        rbd:
          monitors:
          - "192.168.1.9:5000"
          - "192.168.1.8:5000"
          - "192.168.1.5:5000"
          pool: pool_hdd
          image: kube-systemc_gitlab_gitlab
          user: admin
          keyring: /etc/ceph/keyring
          secretRef: null
          fsType: xfs
          readOnly: false
