apiVersion: v1
kind: Service
metadata:
  name: gitlab
  annotations:
    serviceloadbalancer/lb.host: git.36ap.com
  labels:
    app: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - name: http
    port: 80
#  - name: ssh
#    port: 22