"apiVersion": "v1"
"kind": "Pod"
"metadata":
    "name": "centos"

"spec":
    "containers":
     -       "name": "centos-ssh"
            "image": "registry.36ap.com/library/centos-ssh"
            "volumeMounts":
                    "mountPath": "/mnt/rbd"
                    "name": "rbddisk"
    "volumes":
     -       "name": "rbddisk"
            "rbd":
                "monitors":
                - "192.168.1.9:5000"
                - "192.168.1.8:5000"
                - "192.168.1.5:5000"
                "pool": "pool_hdd"
                "image": "kube-system_gitlab_postgresql"
                "user": "admin"
                "keyring": "/etc/ceph/keyring"
                "secretRef":
                "fsType": "xfs"
                "readOnly": false
