apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: email
  namespace: boxlinker
spec:
  rules:
  - host: api.boxlinker.com
    http:
      paths:
      - path: /v1/email
        backend:
          serviceName: email
          servicePort: 8080
  tls:
  - hosts:
    - api.boxlinker.com
    secretName: lb-cert
---
apiVersion: v1
kind: Service
metadata:
  name: email
  namespace: boxlinker
  labels:
    app: "email"
spec:
  ports:
  - port: 8080
  selector:
    app: "email"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: email
  namespace: boxlinker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "email"
    spec:
      imagePullSecrets:
      - name: registry-key
      nodeSelector:
        role: system
      containers:
      - name: email
        image: index.boxlinker.com/boxlinker/email-server:latest
        ports:
        - containerPort: 8080
        args:
        - /email
        - -D
        - --test
        - --mail-host=smtp.exmail.qq.com:25
        - --mail-user=service@boxlinker.com
        - --mail-user-title=Boxlinker
        - --mail-password=Just4fun
        - --mail-type=html
        - --rabbitmq-uri=amqp://guest:guest@rabbitmq:5672/
        - --rabbitmq-exchange=email-server
        - --rabbitmq-queue-name=email-server-queue
        - --rabbitmq-consumer-tag=email-server
        - --rabbitmq-binding-key=email-server-binding-key
#        env:
#        - name: TEST
#          value: "true"
#        - name: DEBUG
#          value: "true"
#        - name: MAIL_HOST
#          value: "smtp.exmail.qq.com:25"
#        - name: MAIL_USER
#          value: "service@boxlinker.com"
#        - name: MAIL_USER_TITLE
#          value: "Boxlinker"
#        - name: MAIL_PASSWORD
#          vaule: "Just4fun"
#        - name: MAIL_TYPE
#          value: "html"
#        - name: RABBITMQ_URI
#          value: "amqp://guest:guest@rabbitmq:5672/"
#        - name: RABBITMQ_EXCHANGE
#          value: "email-server"
#        - name: RABBITMQ_EXCHANGE_TYPE
#          value: "fanout"
#        - name: RABBITMQ_QUEUE_NAME
#          value: "email-server-queue"
#        - name: RABBITMQ_CONSUMER_TAG
#          value: "email-server"
#        - name: RABBITMQ_BINDING_KEY
#          value: "email-server-binding-key"