apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: mariadb-node-1
    namespace: boxlinker
  spec:
    selector:
      component: mariadb-node-1
    ports:
    - port: 4567
      protocol: UDP
      name: port1
    - port: 4568
      protocol: TCP
      name: port2
    - port: 4444
      protocol: TCP
      name: port3
    - port: 4567
      protocol: TCP
      name: port4
- apiVersion: v1
  kind: Service
  metadata:
    name: mariadb-node-2
    namespace: boxlinker
  spec:
    selector:
      component: mariadb-node-2
    ports:
    - port: 4567
      protocol: UDP
      name: port1
    - port: 4568
      protocol: TCP
      name: port2
    - port: 4444
      protocol: TCP
      name: port3
    - port: 4567
      protocol: TCP
      name: port4
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: mariadb-node-1
    namespace: boxlinker
    labels:
      component: mariadb-node-1
  spec:
    replicas: 1
    template:
      metadata:
        name: mariadb-node-1
        labels:
          name: mariadb-node-1
          db-cluster: mariadb
          component: mariadb-node-1
      spec:
        nodeSelector:
          role: loadbalancer
        containers:
        - name: mariadb-node-1
          image: index.boxlinker.com/boxlinker/mariadb-base:10.1
          imagePullPolicy: Always
          ports:
          - containerPort: 3306
            protocol: TCP
          - containerPort: 4567
            protocol: UDP
          - containerPort: 4567
            protocol: TCP
          - containerPort: 4568
            protocol: TCP
          - containerPort: 4444
            protocol: TCP
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: mariadb-node-2
    namespace: boxlinker
    labels:
      component: mariadb-node-2
  spec:
    replicas: 1
    template:
      metadata:
        name: mariadb-node-2
        labels:
          db-cluster: mariadb
          component: mariadb-node-2
          name: mariadb-node-2
      spec:
        nodeSelector:
          role: loadbalancer
        containers:
        - name: mariadb-node-2
          image: index.boxlinker.com/boxlinker/mariadb-base:10.1
          imagePullPolicy: Always
          env:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "my-secret-pwd"
          ports:
          - containerPort: 3306
            protocol: TCP
          - containerPort: 4567
            protocol: UDP
          - containerPort: 4567
            protocol: TCP
          - containerPort: 4568
            protocol: TCP
          - containerPort: 4444
            protocol: TCP

