apiVersion: v1
kind: Pod
metadata:
  name: mariadb-test
spec:
  nodeSelector:
    role: loadbalancer
  containers:
  - name: mariadb-test
    image: index.boxlinker.com/boxlinker/mariadb-base:10.1
    command:
    - sleep
    - "3600"
