apiVersion: v1
kind: Service
metadata:
    name: rabbitmq03
    labels:
        name: rabbitmq03
spec:
    selector:
        name: rabbitmq03
    ports:
    - name: rabbitmq
      port: 5672
      targetPort: 5672
    - name: cluster
      port: 4369
      targetPort: 4369
    - name: mqcluster
      port: 25672
      targetPort: 25672
