apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  namespace: default
  labels:
    component: elk
    role: kibana
spec:
  replicas: 1
  selector:
    component: elk
    role: kibana
  template:
    metadata:
      labels:
        component: elk
        role: kibana
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: kibana
        image: kibana
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch.default.svc:9200"
        ports:
        - containerPort: 5601
          hostPort: 80
          name: http
          protocol: TCP
